/**
 * @file lang_config.h
 * @author Tuya Inc.
 * @brief Bilingual language config for Tuya AI components UI
 *
 * Generated by tools/gen_bilingual_lang_header.py from upstream TuyaOpen's
 * src/ai_components/assets/language/{en-US,zh-CN}/language.json.
 * Do not edit by hand; regenerate against the upstream revision being
 * packaged. LANG_CONF semantics: undefined or 1 = English, 0 = Chinese.
 * This file is exempted from the no-Chinese-characters CI check via
 * .clang-format-ignore.
 *
 * @copyright Copyright (c) 2021-2026 Tuya Inc. All Rights Reserved.
 *
 */
#ifndef __LANGUAGE_CONFIG_H__
#define __LANGUAGE_CONFIG_H__

#ifdef __cplusplus
extern "C" {
#endif

#if !defined(LANG_CONF) || (LANG_CONF == 1)

#ifndef en_us
#define en_us
#endif

#define LANG_CODE "en-US"

#define VERSION                       "Version "
#define INITIALIZING                  "Initializing..."
#define PROVISIONING                  "Provisioning..."
#define REGISTERING_NETWORK           "Waiting for network..."
#define CONNECT_SERVER                "Connecting to server..."
#define STANDBY                       "Standby"
#define CONNECT_TO                    "Connect to "
#define CONNECTING                    "Connecting..."
#define CONNECTED_TO                  "Connected to "
#define LISTENING                     "Listening..."
#define UPLOADING                     "Uploading..."
#define THINKING                      "Thinking..."
#define SPEAKING                      "Speaking..."
#define HOLD_TALK                     "Hold"
#define TRIG_TALK                     "Press"
#define WAKEUP_TALK                   "Wake up"
#define FREE_TALK                     "Free"
#define ENTERING_WIFI_CONFIG_MODE     "Entering Wi-Fi configuration mode..."
#define VOLUME                        "Volume "
#define MUTED                         "Muted"
#define MAX_VOLUME                    "Max Volume"
#define SYSTEM_MSG_POWER_ON           "Power on"
#define SYSTEM_MSG_WIFI_SSID          "WiFi connected"
#define SYSTEM_MSG_IP                 "IP address is"
#define SYSTEM_MSG_WIFI_DISCONNECTED  "WiFi disconnected"
#define SYSTEM_MSG_VOLUME             "Volume set to"
#define VIEW_IMAGE                    "View Image"
#define NO_IMAGE                      "No Images"
#define TAKE_PHOTO                    "Take Photo"
#define ADD_IMAGE                     "Add Image"
#define PRINT_IMAGE                   "Print Image"
#define PRINTING                      "Printing..."
#define PRINT_SUCCESS                 "Print success"
#define PRINT_FAILED                  "Print failed"
#define CAMERA                        "Camera"
#define ALBUM                         "Album"
#define CANCEL                        "Cancel"
#define ALL_PHOTOS                    "All Photos"
#define SELECT_TEXT                   "Select"
#define DELETE_TEXT                   "Delete"
#define CONFIRM_TEXT                  "Confirm"
#define RECOGNIZE_IMAGE_PROMPT        "explain the content of the uploaded image, do not trigger MCP skills, do not call MCP tools"

#else // LANG_CONF == 0

#ifndef zh_cn
#define zh_cn
#endif

#define LANG_CODE "zh-CN"

#define VERSION                       "版本 "
#define INITIALIZING                  "正在初始化..."
#define PROVISIONING                  "配网中..."
#define REGISTERING_NETWORK           "等待网络..."
#define CONNECT_SERVER                "连接服务器..."
#define STANDBY                       "待命"
#define CONNECT_TO                    "连接 "
#define CONNECTING                    "连接中..."
#define CONNECTED_TO                  "已连接 "
#define LISTENING                     "聆听中..."
#define UPLOADING                     "上传中..."
#define THINKING                      "思考中..."
#define SPEAKING                      "说话中..."
#define HOLD_TALK                     "长按"
#define TRIG_TALK                     "按键"
#define WAKEUP_TALK                   "唤醒"
#define FREE_TALK                     "随意"
#define ENTERING_WIFI_CONFIG_MODE     "进入配网模式..."
#define VOLUME                        "音量 "
#define MUTED                         "已静音"
#define MAX_VOLUME                    "最大音量"
#define SYSTEM_MSG_POWER_ON           "开机"
#define SYSTEM_MSG_WIFI_SSID          "WiFi 已连接"
#define SYSTEM_MSG_IP                 "IP 地址为"
#define SYSTEM_MSG_WIFI_DISCONNECTED  "WiFi 断开连接"
#define SYSTEM_MSG_VOLUME             "音量设置为"
#define VIEW_IMAGE                    "查看图片"
#define NO_IMAGE                      "暂无图片"
#define TAKE_PHOTO                    "拍照"
#define ADD_IMAGE                     "添加图片"
#define PRINT_IMAGE                   "打印图片"
#define PRINTING                      "打印中..."
#define PRINT_SUCCESS                 "打印成功"
#define PRINT_FAILED                  "打印失败"
#define CAMERA                        "相机"
#define ALBUM                         "相册"
#define CANCEL                        "取消"
#define ALL_PHOTOS                    "所有照片"
#define SELECT_TEXT                   "选择"
#define DELETE_TEXT                   "删除"
#define CONFIRM_TEXT                  "确认"
#define RECOGNIZE_IMAGE_PROMPT        "请解释上传图片的内容，不要触发MCP技能，不要调用MCP工具"

#endif // LANG_CONF

#ifdef __cplusplus
}
#endif

#endif // !__LANGUAGE_CONFIG_H__
