#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate the bilingual libraries/AIcomponents/src/lang_config.h.

Merges upstream TuyaOpen's en-US and zh-CN language.json into a single
header gated on LANG_CONF (undefined/1 = English, 0 = Chinese).

Usage:
    python tools/gen_bilingual_lang_header.py --tuyaopen <path-to-TuyaOpen-checkout>
"""
import argparse
import json
import os
import sys

FILE_HEADER = """/**
 * @file lang_config.h
 * @author Tuya Inc.
 * @brief Bilingual language config for Tuya AI components UI
 *
 * Generated by tools/gen_bilingual_lang_header.py from upstream TuyaOpen's
 * src/ai_components/assets/language/{en-US,zh-CN}/language.json.
 * Do not edit by hand; regenerate against the upstream revision being
 * packaged. LANG_CONF semantics: undefined or 1 = English, 0 = Chinese.
 * This file is exempted from the no-Chinese-characters CI check via
 * .clang-format-ignore.
 *
 * @copyright Copyright (c) 2021-2026 Tuya Inc. All Rights Reserved.
 *
 */
#ifndef __LANGUAGE_CONFIG_H__
#define __LANGUAGE_CONFIG_H__

#ifdef __cplusplus
extern "C" {
#endif
"""

FILE_FOOTER = """
#ifdef __cplusplus
}
#endif

#endif // !__LANGUAGE_CONFIG_H__
"""


def load_language(tuyaopen, lang_dir):
    path = os.path.join(
        tuyaopen, "src", "ai_components", "assets", "language", lang_dir, "language.json"
    )
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    return data["language"]["type"], data["strings"]


def emit_block(lang_code, strings):
    guard = lang_code.lower().replace("-", "_")
    width = max(len(k) for k in strings) + 1
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "#endif",
        "",
        f'#define LANG_CODE {json.dumps(lang_code)}',
        "",
    ]
    for key, value in strings.items():
        literal = json.dumps(value, ensure_ascii=False)
        lines.append(f"#define {key:<{width}} {literal}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--tuyaopen", required=True, help="Path to a TuyaOpen checkout")
    parser.add_argument(
        "--output",
        default=os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "libraries", "AIcomponents", "src", "lang_config.h",
        ),
    )
    args = parser.parse_args()

    en_code, en_strings = load_language(args.tuyaopen, "en-US")
    zh_code, zh_strings = load_language(args.tuyaopen, "zh-CN")

    if set(en_strings) != set(zh_strings):
        diff = set(en_strings) ^ set(zh_strings)
        sys.exit(f"error: en/zh key sets differ: {sorted(diff)}")

    content = "\n".join([
        FILE_HEADER,
        "#if !defined(LANG_CONF) || (LANG_CONF == 1)",
        "",
        emit_block(en_code, en_strings),
        "",
        "#else // LANG_CONF == 0",
        "",
        emit_block(zh_code, zh_strings),
        "",
        "#endif // LANG_CONF",
        FILE_FOOTER,
    ])
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Wrote {args.output} ({len(en_strings)} keys per language)")


if __name__ == "__main__":
    main()
